services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ridepack-backend
    ports:
      - "5000:3000"
    env_file:
      - .env
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - ridepack-network

networks:
  ridepack-network:
    driver: bridge
